apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  completions: 1 #How many time to run
  parallelism: 1 #How many pods to create
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh", "-c", "echo Hello World! && sleep 10"]
      restartPolicy: Never


